"""remove columns

Revision ID: 4b078a0871f7
Revises: 86d476979c63
Create Date: 2025-12-23 22:08:51.223127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b078a0871f7'
down_revision: Union[str, Sequence[str], None] = '86d476979c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier_service_tariff_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('version', sa.SmallInteger(), nullable=False, comment='版本号'),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True, comment='生效时间'),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True, comment='失效时间'),
    sa.Column('carrier_id', sa.BigInteger(), nullable=False, comment='承运商ID'),
    sa.Column('service_id', sa.BigInteger(), nullable=False, comment='运输服务ID'),
    sa.Column('carrier_code', sa.String(length=64), nullable=False, comment='承运商编码'),
    sa.Column('service_code', sa.String(length=64), nullable=False, comment='运输服务编码'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='运费二维矩阵结构'),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False, comment='快照状态'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['carrier_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrier_id', 'service_id', 'version', name='uq_carrier_tariff_snapshot_version')
    )
    op.create_index('idx_carrier_tariff_snapshot_effective', 'carrier_service_tariff_snapshots', ['effective_from'], unique=False)
    op.create_index('idx_carrier_tariff_snapshot_lookup', 'carrier_service_tariff_snapshots', ['carrier_code', 'service_code', 'effective_from'], unique=False)
    op.create_index('idx_carrier_tariff_snapshot_service', 'carrier_service_tariff_snapshots', ['carrier_id', 'service_id'], unique=False)
    op.create_table('carrier_service_tariffs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('carrier_service_id', sa.BigInteger(), nullable=False, comment='关联承运商服务'),
    sa.Column('region_code', sa.String(length=64), nullable=False, comment='目的地区域编码'),
    sa.Column('weight_max_kg', sa.Float(), nullable=True, comment='重量上限(kg)'),
    sa.Column('volume_max_cm3', sa.Integer(), nullable=True, comment='体积上限(cm^3)'),
    sa.Column('girth_max_cm', sa.Integer(), nullable=True, comment='三边合计上限(cm)'),
    sa.Column('currency', sa.String(length=8), server_default='JPY', nullable=False, comment='币种'),
    sa.Column('price_amount', sa.BigInteger(), nullable=False, comment='价格(最小货币单位)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['carrier_service_id'], ['carrier_services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_code'], ['regions.region_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrier_service_id', 'region_code', 'weight_max_kg', 'volume_max_cm3', 'girth_max_cm', name='uq_carrier_tariff_dimension')
    )
    op.create_index('idx_carrier_tariff_region', 'carrier_service_tariffs', ['region_code'], unique=False)
    op.drop_column('carrier_service_geo_groups', 'expire_date')
    op.drop_column('carrier_service_geo_groups', 'effective_date')
    op.drop_column('carrier_services', 'coverage_group_code')
    op.drop_column('carrier_services', 'effective_date')
    op.drop_column('carrier_services', 'expire_date')
    op.drop_column('carrier_services', 'service_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrier_services', sa.Column('service_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='运输服务类型'))
    op.add_column('carrier_services', sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='失效时间'))
    op.add_column('carrier_services', sa.Column('effective_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='生效时间'))
    op.add_column('carrier_services', sa.Column('coverage_group_code', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='覆盖分组编码'))
    op.add_column('carrier_service_geo_groups', sa.Column('effective_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='生效时间'))
    op.add_column('carrier_service_geo_groups', sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='失效时间'))
    op.drop_index('idx_carrier_tariff_region', table_name='carrier_service_tariffs')
    op.drop_table('carrier_service_tariffs')
    op.drop_index('idx_carrier_tariff_snapshot_service', table_name='carrier_service_tariff_snapshots')
    op.drop_index('idx_carrier_tariff_snapshot_lookup', table_name='carrier_service_tariff_snapshots')
    op.drop_index('idx_carrier_tariff_snapshot_effective', table_name='carrier_service_tariff_snapshots')
    op.drop_table('carrier_service_tariff_snapshots')
    # ### end Alembic commands ###
