"""update geo_group_id

Revision ID: 6676dc7128f4
Revises: 4b078a0871f7
Create Date: 2025-12-24 00:09:32.476145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6676dc7128f4'
down_revision: Union[str, Sequence[str], None] = '4b078a0871f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrier_service_tariffs', sa.Column('geo_group_id', sa.BigInteger(), nullable=False, comment='关联覆盖分组ID'))
    op.drop_index(op.f('idx_carrier_tariff_region'), table_name='carrier_service_tariffs')
    op.drop_constraint(op.f('uq_carrier_tariff_dimension'), 'carrier_service_tariffs', type_='unique')
    op.create_unique_constraint('uq_carrier_tariff_dimension', 'carrier_service_tariffs', ['carrier_service_id', 'geo_group_id', 'weight_max_kg', 'volume_max_cm3', 'girth_max_cm'])
    op.create_index('idx_carrier_tariff_geo_group', 'carrier_service_tariffs', ['geo_group_id'], unique=False)
    op.drop_constraint(op.f('carrier_service_tariffs_region_code_fkey'), 'carrier_service_tariffs', type_='foreignkey')
    op.create_foreign_key(None, 'carrier_service_tariffs', 'carrier_service_geo_groups', ['geo_group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('carrier_service_tariffs', 'region_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carrier_service_tariffs', sa.Column('region_code', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='目的地区域编码'))
    op.drop_constraint(None, 'carrier_service_tariffs', type_='foreignkey')
    op.create_foreign_key(op.f('carrier_service_tariffs_region_code_fkey'), 'carrier_service_tariffs', 'regions', ['region_code'], ['region_code'])
    op.drop_index('idx_carrier_tariff_geo_group', table_name='carrier_service_tariffs')
    op.drop_constraint('uq_carrier_tariff_dimension', 'carrier_service_tariffs', type_='unique')
    op.create_unique_constraint(op.f('uq_carrier_tariff_dimension'), 'carrier_service_tariffs', ['carrier_service_id', 'region_code', 'weight_max_kg', 'volume_max_cm3', 'girth_max_cm'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_carrier_tariff_region'), 'carrier_service_tariffs', ['region_code'], unique=False)
    op.drop_column('carrier_service_tariffs', 'geo_group_id')
    # ### end Alembic commands ###
