"""template rule

Revision ID: 83d127211428
Revises: 9fb96aadca3b
Create Date: 2025-12-09 13:21:00.690529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83d127211428'
down_revision: Union[str, Sequence[str], None] = '9fb96aadca3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_code', sa.String(length=64), nullable=False),
    sa.Column('template_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('template_type', sa.String(length=16), nullable=False),
    sa.Column('business_domain', sa.String(length=64), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('customer_group_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['business_domain'], ['business_domains.code'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_code', name='uq_billing_template_code')
    )
    op.create_index('idx_billing_template_customer', 'billing_templates', ['customer_id'], unique=False)
    op.create_index('idx_billing_template_group_ids', 'billing_templates', ['customer_group_ids'], unique=False, postgresql_using='gin')
    op.create_index('idx_billing_template_type', 'billing_templates', ['template_type'], unique=False)
    op.create_table('billing_quotes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('quote_code', sa.String(length=64), nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=16), nullable=False),
    sa.Column('scope_priority', sa.SmallInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('customer_group_id', sa.BigInteger(), nullable=True),
    sa.Column('business_domain', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='ACTIVE', nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['business_domain'], ['business_domains.code'], ),
    sa.ForeignKeyConstraint(['customer_group_id'], ['customer_groups.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['billing_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_code', name='uq_billing_quote_code')
    )
    op.create_index('idx_billing_quotes_customer', 'billing_quotes', ['customer_id'], unique=False)
    op.create_index('idx_billing_quotes_group', 'billing_quotes', ['customer_group_id'], unique=False)
    op.create_index('idx_billing_quotes_template_id', 'billing_quotes', ['template_id'], unique=False)
    op.create_table('billing_template_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.BigInteger(), nullable=False),
    sa.Column('charge_code', sa.String(length=64), nullable=False),
    sa.Column('charge_name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('pricing_mode', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('support_only', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['billing_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_rules_template_id', 'billing_template_rules', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_template_rules_template_id', table_name='billing_template_rules')
    op.drop_table('billing_template_rules')
    op.drop_index('idx_billing_quotes_template_id', table_name='billing_quotes')
    op.drop_index('idx_billing_quotes_group', table_name='billing_quotes')
    op.drop_index('idx_billing_quotes_customer', table_name='billing_quotes')
    op.drop_table('billing_quotes')
    op.drop_index('idx_billing_template_type', table_name='billing_templates')
    op.drop_index('idx_billing_template_group_ids', table_name='billing_templates', postgresql_using='gin')
    op.drop_index('idx_billing_template_customer', table_name='billing_templates')
    op.drop_table('billing_templates')
    # ### end Alembic commands ###
