"""remove version

Revision ID: 84d152eb5b27
Revises: e7f5ac0f5ab9
Create Date: 2025-12-09 23:23:28.670194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d152eb5b27'
down_revision: Union[str, Sequence[str], None] = 'e7f5ac0f5ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_quotes', 'template_version')
    op.drop_column('billing_templates', 'version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_templates', sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('billing_quotes', sa.Column('template_version', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
