"""add geo group

Revision ID: 86d476979c63
Revises: ffb2e5806944
Create Date: 2025-12-14 21:47:09.030831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86d476979c63'
down_revision: Union[str, Sequence[str], None] = 'ffb2e5806944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier_service_geo_groups',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('carrier_service_id', sa.BigInteger(), nullable=False, comment='关联运输服务ID'),
    sa.Column('group_code', sa.String(length=64), nullable=False, comment='虚拟区域分组编码'),
    sa.Column('group_name', sa.String(length=128), nullable=False, comment='虚拟区域分组名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='虚拟区域分组描述'),
    sa.Column('status', sa.String(), server_default='SCHEDULED', nullable=False, comment='分组状态'),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True, comment='生效时间'),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True, comment='失效时间'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='分组扩展信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['carrier_service_id'], ['carrier_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_code', name='uq_carrier_geo_group_code')
    )
    op.create_index('idx_carrier_geo_group_service', 'carrier_service_geo_groups', ['carrier_service_id'], unique=False)
    op.create_index('uq_active_carrier_geo_group', 'carrier_service_geo_groups', ['carrier_service_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('carrier_service_geo_group_regions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='虚拟区域分组ID'),
    sa.Column('region_code', sa.String(length=64), nullable=False, comment='Region 区域编码'),
    sa.Column('region_level', sa.String(), nullable=True, comment='区域层级'),
    sa.Column('priority', sa.SmallInteger(), nullable=True, comment='匹配优先级'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='覆盖范围扩展信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['carrier_service_geo_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['region_code'], ['regions.region_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'region_code', name='uq_geo_group_region_code')
    )
    op.create_index('idx_geo_group_region_group_id', 'carrier_service_geo_group_regions', ['group_id'], unique=False)
    op.alter_column('carrier_services', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='carrierservicestatus'),
               type_=sa.String(),
               existing_comment='运输服务状态',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::carrierservicestatus"))
    op.alter_column('carriers', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', name='carrierstatus'),
               type_=sa.String(),
               existing_comment='服务商状态',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::carrierstatus"))
    op.alter_column('regions', 'level',
               existing_type=postgresql.ENUM('COUNTRY', 'PREFECTURE', 'CITY', 'DISTRICT', 'TOWN', name='regionlevel'),
               type_=sa.String(),
               existing_comment='行政层级',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('regions', 'level',
               existing_type=sa.String(),
               type_=postgresql.ENUM('COUNTRY', 'PREFECTURE', 'CITY', 'DISTRICT', 'TOWN', name='regionlevel'),
               existing_comment='行政层级',
               existing_nullable=False)
    op.alter_column('carriers', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ACTIVE', 'INACTIVE', name='carrierstatus'),
               existing_comment='服务商状态',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::carrierstatus"))
    op.alter_column('carrier_services', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED', name='carrierservicestatus'),
               existing_comment='运输服务状态',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::carrierservicestatus"))
    op.drop_index('idx_geo_group_region_group_id', table_name='carrier_service_geo_group_regions')
    op.drop_table('carrier_service_geo_group_regions')
    op.drop_index('uq_active_carrier_geo_group', table_name='carrier_service_geo_groups', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('idx_carrier_geo_group_service', table_name='carrier_service_geo_groups')
    op.drop_table('carrier_service_geo_groups')
    # ### end Alembic commands ###
