"""update group ids to group id

Revision ID: ca454c4877c4
Revises: 83d127211428
Create Date: 2025-12-09 18:53:36.146146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca454c4877c4'
down_revision: Union[str, Sequence[str], None] = '83d127211428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billing_template_rules', 'price',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billing_template_rules', 'price',
               existing_type=sa.BigInteger(),
               type_=sa.NUMERIC(precision=18, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###
