"""update billing template

Revision ID: e7f5ac0f5ab9
Revises: ca454c4877c4
Create Date: 2025-12-09 21:06:00.069877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7f5ac0f5ab9'
down_revision: Union[str, Sequence[str], None] = 'ca454c4877c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_templates', sa.Column('customer_group_id', sa.BigInteger(), nullable=True))
    op.drop_index(op.f('idx_billing_template_group_ids'), table_name='billing_templates', postgresql_using='gin')
    op.create_index('idx_billing_template_group_id', 'billing_templates', ['customer_group_id'], unique=False)
    op.create_foreign_key(None, 'billing_templates', 'customer_groups', ['customer_group_id'], ['id'])
    op.drop_column('billing_templates', 'customer_group_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_templates', sa.Column('customer_group_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'billing_templates', type_='foreignkey')
    op.drop_index('idx_billing_template_group_id', table_name='billing_templates')
    op.create_index(op.f('idx_billing_template_group_ids'), 'billing_templates', ['customer_group_ids'], unique=False, postgresql_using='gin')
    op.drop_column('billing_templates', 'customer_group_id')
    # ### end Alembic commands ###
