"""add regions

Revision ID: ffb2e5806944
Revises: 84d152eb5b27
Create Date: 2025-12-14 14:47:45.478868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffb2e5806944'
down_revision: Union[str, Sequence[str], None] = '84d152eb5b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('carrier_code', sa.String(length=64), nullable=False, comment='服务商编码'),
    sa.Column('carrier_name', sa.String(length=128), nullable=False, comment='服务商名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='服务商描述'),
    sa.Column('country_code', sa.String(length=8), server_default='JP', nullable=False, comment='所属国家/地区'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='carrierstatus'), server_default='ACTIVE', nullable=False, comment='服务商状态'),
    sa.Column('contact_email', sa.String(length=128), nullable=True, comment='联系人邮箱'),
    sa.Column('contact_phone', sa.String(length=32), nullable=True, comment='联系人电话'),
    sa.Column('website', sa.String(length=128), nullable=True, comment='官网地址'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='服务商扩展信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrier_code', name='uq_carrier_code')
    )
    op.create_table('regions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('region_code', sa.String(length=64), nullable=False, comment='区域编码（行政区划代码）'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='区域名称（标准）'),
    sa.Column('country_code', sa.String(length=8), server_default='JP', nullable=False, comment='所属国家代码'),
    sa.Column('level', sa.Enum('COUNTRY', 'PREFECTURE', 'CITY', 'DISTRICT', 'TOWN', name='regionlevel'), nullable=False, comment='行政层级'),
    sa.Column('parent_code', sa.String(length=64), nullable=True, comment='父级区域编码'),
    sa.Column('postal_code_prefix', sa.String(length=16), nullable=True, comment='邮编前缀'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='自定义扩展字段'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region_code', name='uq_regions_region_code')
    )
    op.create_index('idx_regions_country_level', 'regions', ['country_code', 'level'], unique=False)
    op.create_index('idx_regions_parent_code', 'regions', ['parent_code'], unique=False)
    op.create_table('carrier_services',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('carrier_id', sa.BigInteger(), nullable=False, comment='所属服务商ID'),
    sa.Column('service_code', sa.String(length=64), nullable=False, comment='运输服务编码'),
    sa.Column('service_name', sa.String(length=128), nullable=False, comment='运输服务名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='运输服务描述'),
    sa.Column('service_type', sa.String(length=32), nullable=False, comment='运输服务类型'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='carrierservicestatus'), server_default='ACTIVE', nullable=False, comment='运输服务状态'),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True, comment='生效时间'),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True, comment='失效时间'),
    sa.Column('coverage_group_code', sa.String(length=64), nullable=True, comment='覆盖分组编码'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='服务扩展信息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_by_id', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by_id', sa.String(length=64), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=64), nullable=True),
    sa.Column('deleted_by_id', sa.String(length=64), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrier_id', 'service_code', name='uq_carrier_service_code')
    )
    op.create_index('idx_carrier_services_status', 'carrier_services', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_carrier_services_status', table_name='carrier_services')
    op.drop_table('carrier_services')
    op.drop_index('idx_regions_parent_code', table_name='regions')
    op.drop_index('idx_regions_country_level', table_name='regions')
    op.drop_table('regions')
    op.drop_table('carriers')
    # ### end Alembic commands ###
